# Kadai Store API v1.0.0
# 基本的な設定

# デフォルトとして、推奨値を入れてあります。ご参考にしてください。

# MS Teamsから課題情報を取得する、時間の間隔(分)をここで指定します。
# 1 以上の整数を入れてください。
update_duration: 5

# MS Teamsから課題情報を取得しない、時(hour)があれば、ここで指定します。(複数指定可)
# 0 から 23 の中の整数を入れてください。指定がない場合は [] にしてください。
update_offtimes: [0, 1, 2, 3, 4, 5, 6, 7, 18, 19, 20, 21, 22, 23]

# 1つのトークンが、 get_limit_duration で指定する期間内に、このAPI(/get)にGETできる回数をここで指定します。(レート制限)
# 1 以上の整数もしくは -1 を入れてください。指定しない場合は -1 を入れてください。
get_limit: 60

# get_limit の期間(分)をここで指定します。
# 1 以上の整数もしくは -1 を入れてください。get_limit で指定していない場合は -1 を入れてください。
get_limit_duration: 10

# 一時的なデータを保管するディレクトリをここで指定します。
#   Herokuを使用する場合: ./tmp/api-data
#   Google App Engineを使用する場合: ./tmp/api-data
tmp-dir: ./tmp/api-data

# UTC(協定世界時)以外に扱うタイムゾーンをここで指定します。
# 利用可能なタイムゾーンは https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List の
# TZ database name をご覧ください。
timezones:
  - Asia/Tokyo
  - Asia/Ulaanbaatar
  - Asia/Bangkok

# 取得する課題が格納されているチーム名と、教科名、教科IDをここで指定します。
# 同じ教科の複数のチームがある場合は、教科名と教科IDを同じにし、チーム名を全てお書きください。
#   チーム名: MS Teamsで確認することができる、チーム名
#   教科名:   シラバスに記載されている教科名 (任意の名前)
#   ID:      URLクエリパラメータで、教科を指定するためのID (任意の名前)
# 配列の0番目にチーム名、1番目に教科名、2番目にIDを入れてください。
subjects:
  - ["[099]J2HR2020", "HR", "hr"]
  - ["[099] (5/8まで)国語総合", "国語総合", "japanese"]
  - ["[099] 国語総合", "国語総合", "japanese"]
  - ["【099】基礎数学4", "基礎数学４", "math3"]
  - ["【099】物理B", "物理Ｂ", "physics-b"]
  - ["[099] 法学2", "法学２", "law2"]
  - ["(099) LE1", "level Up English 1", "le1"]
  - ["[099]英会話1", "英会話１", "eikaiwa1"]
  - ["[099] J2 アルゴリズム", "アルゴリズム", "algorithm"]
  - ["[099] Webアプリケーション", "Webアプリケーション", "web"]
  - ["[099] Webアプリケーション (20番~30番)", "Webアプリケーション", "web"]
  - ["[099] Webアプリケーション (20番~40番)", "Webアプリケーション", "web"]
  - ["[099] 2年生 AI基礎", "AI基礎", "web"]
  - ["【099】　電気電子回路", "電気電子回路", "circuit"]
  - ["(099)犬工学", "犬工学", "dog"]
  - ["(099)猫工学", "猫工学", "cat"]

# 当APIにアクセスを許可するトークンをここで指定します。(任意の文字列)
# ここで定めたものを、API利用者にお伝えください。
allow-tokens:
  - 12345678abc9cba87654321
  - 98765432abc1cba23456789